-- MySQL Script generated by MySQL Workbench
-- Mon May 14 14:36:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema drplace_portaldev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema drplace_portaldev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drplace_portaldev` DEFAULT CHARACTER SET utf8 ;
USE `drplace_portaldev` ;

-- -----------------------------------------------------
-- Table `drplace_portaldev`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drplace_portaldev`.`cidade` (
  `cid_id` INT NOT NULL AUTO_INCREMENT,
  `cid_sigla` CHAR(2) NOT NULL,
  `cid_nome` VARCHAR(100) NOT NULL,
  `cid_anuncio` TINYINT(1) NOT NULL DEFAULT 0,
  `cid_status` TINYINT(1) NOT NULL DEFAULT 1,
  `cid_statusAtivo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`cid_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `drplace_portaldev`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drplace_portaldev`.`usuario_perfil` (
  `uperf_id` INT NOT NULL AUTO_INCREMENT,
  `uperf_nome` VARCHAR(120) NOT NULL,
  `uperf_status` TINYINT(1) NOT NULL DEFAULT 1,
  `uperf_statusAtivo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`uperf_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `drplace_portaldev`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drplace_portaldev`.`usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `fk_id_cidade` INT NULL,
  `fk_id_perfil` INT NOT NULL,
  `usu_token` CHAR(128) NOT NULL,
  `usu_nome` VARCHAR(160) NULL,
  `usu_cpf` CHAR(14) NULL,
  `usu_senha` CHAR(64) NULL,
  `usu_rg` VARCHAR(25) NULL,
  `usu_endereco` VARCHAR(140) NULL,
  `usu_numero` VARCHAR(25) NULL,
  `usu_bairro` VARCHAR(80) NULL,
  `usu_complemento` VARCHAR(60) NULL,
  `usu_cep` CHAR(10) NULL,
  `usu_dataCadastro` DATETIME NOT NULL,
  `usu_telefone1` CHAR(14) NULL,
  `usu_telefone2` CHAR(14) NULL,
  `usu_celular1` VARCHAR(15) NULL,
  `usu_celular2` VARCHAR(15) NULL,
  `usu_whatsapp1` VARCHAR(15) NULL,
  `usu_whatsapp2` VARCHAR(15) NULL,
  `usu_radio1` VARCHAR(15) NULL,
  `usu_site` VARCHAR(120) NULL,
  `usu_facebook` VARCHAR(120) NULL,
  `usu_instagram` VARCHAR(120) NULL,
  `usu_twitter` VARCHAR(120) NULL,
  `usu_email1` VARCHAR(100) NOT NULL,
  `usu_email2` VARCHAR(100) NULL,
  `usu_confirmado` TINYINT(1) NOT NULL DEFAULT 0,
  `usu_status` TINYINT(1) NOT NULL DEFAULT 1,
  `usu_statusAtivo` TINYINT(1) NOT NULL DEFAULT 1,
  `usu_admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`usu_id`),
  INDEX `fk_cliente_cidade_idx` (`fk_id_cidade` ASC),
  INDEX `fk_usuario_usuario_perfil1_idx` (`fk_id_perfil` ASC),
  CONSTRAINT `fk_cliente_cidade`
    FOREIGN KEY (`fk_id_cidade`)
    REFERENCES `drplace_portaldev`.`cidade` (`cid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario_perfil1`
    FOREIGN KEY (`fk_id_perfil`)
    REFERENCES `drplace_portaldev`.`usuario_perfil` (`uperf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `drplace_portaldev`.`log_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drplace_portaldev`.`log_acesso` (
  `logace_id` INT NOT NULL AUTO_INCREMENT,
  `fk_id_usuario` INT NOT NULL,
  `logace_data` DATETIME NOT NULL,
  `logace_enderecoIp` VARCHAR(45) NOT NULL,
  `logace_navegador` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`logace_id`),
  INDEX `fk_log_acesso_usuario1_idx` (`fk_id_usuario` ASC),
  CONSTRAINT `fk_log_acesso_usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `drplace_portaldev`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `drplace_portaldev`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drplace_portaldev`.`imovel` (
  `imo_id` INT NOT NULL AUTO_INCREMENT,
  `fk_id_usuario` INT NOT NULL,
  `fk_id_cidade` INT NOT NULL,
  `imo_codigo` VARCHAR(20) NULL,
  `imo_titulo` VARCHAR(100) NULL,
  `imo_descricao` MEDIUMTEXT NULL,
  `imo_logradouro` VARCHAR(160) NULL,
  `imo_numero` VARCHAR(20) NULL,
  `imo_bairro` VARCHAR(80) NULL,
  `imo_complemento` VARCHAR(80) NULL,
  `imo_cep` CHAR(9) NULL,
  `imo_valor` DOUBLE(10,2) NULL,
  `imo_dataCadastro` DATETIME NOT NULL,
  `imo_dataEdicao` DATETIME NULL,
  `imo_ultimaReforma` DATE NULL,
  `imo_construcao` DATE NULL,
  `imo_situacao` CHAR(1) NOT NULL COMMENT 'A = Aluguel\nV = Venda\nF = Finalizado',
  `imo_status` TINYINT(1) NOT NULL DEFAULT 1,
  `imo_valorIptu` DOUBLE(6,2) NULL,
  `imo_valorCondominio` DOUBLE(6,2) NULL,
  PRIMARY KEY (`imo_id`),
  INDEX `fk_imovel_usuario1_idx` (`fk_id_usuario` ASC),
  INDEX `fk_imovel_cidade1_idx` (`fk_id_cidade` ASC),
  CONSTRAINT `fk_imovel_usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `drplace_portaldev`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_cidade1`
    FOREIGN KEY (`fk_id_cidade`)
    REFERENCES `drplace_portaldev`.`cidade` (`cid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `drplace_portaldev`.`imovel_caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drplace_portaldev`.`imovel_caracteristica` (
  `fk_id_imovel` INT NOT NULL,
  `imcar_proxViaAcesso` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_proxEscola` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_proxTransPub` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_proxHospital` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_proxShopping` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_quintal` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_garagem` INT(2) NOT NULL DEFAULT 0,
  `imcar_sacada` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_cozinha` INT(2) NOT NULL DEFAULT 0,
  `imcar_areaServico` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_internet` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_interfone` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_condominioFechado` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_condominioAberto` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_churrasqueira` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_jardim` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_piscina` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_parque` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_quadraPoliesportiva` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_espacoGourmet` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_segurancaFullTime` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_circuitoSeguranca` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_arCondicionado` TINYINT(1) NOT NULL DEFAULT 0,
  `imcar_dormitorio` INT(2) NOT NULL DEFAULT 0,
  `imcar_banheiro` INT(2) NOT NULL DEFAULT 0,
  `imcar_area` INT(6) NOT NULL DEFAULT 0,
  `imcar_suite` INT(2) NOT NULL DEFAULT 0,
  INDEX `fk_imovel_caracteristicas_imovel1_idx` (`fk_id_imovel` ASC),
  CONSTRAINT `fk_imovel_caracteristicas_imovel1`
    FOREIGN KEY (`fk_id_imovel`)
    REFERENCES `drplace_portaldev`.`imovel` (`imo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `drplace_portaldev`.`imovel_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drplace_portaldev`.`imovel_acesso` (
  `fk_id_imovel` INT NOT NULL,
  `fk_id_usuario` INT NULL,
  `imace_enderecoIp` VARCHAR(60) NOT NULL,
  `imace_userAgent` VARCHAR(140) NOT NULL,
  `imace_data` DATETIME NOT NULL,
  INDEX `fk_rel_imovel_acesso_imovel1_idx` (`fk_id_imovel` ASC),
  INDEX `fk_rel_imovel_acesso_usuario1_idx` (`fk_id_usuario` ASC),
  CONSTRAINT `fk_rel_imovel_acesso_imovel1`
    FOREIGN KEY (`fk_id_imovel`)
    REFERENCES `drplace_portaldev`.`imovel` (`imo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rel_imovel_acesso_usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `drplace_portaldev`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `drplace_portaldev`.`cidade`
-- -----------------------------------------------------
START TRANSACTION;
USE `drplace_portaldev`;
INSERT INTO `drplace_portaldev`.`cidade` (`cid_id`, `cid_sigla`, `cid_nome`, `cid_anuncio`, `cid_status`, `cid_statusAtivo`) VALUES (1, 'AD', 'À DEFINIR', DEFAULT, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `drplace_portaldev`.`usuario_perfil`
-- -----------------------------------------------------
START TRANSACTION;
USE `drplace_portaldev`;
INSERT INTO `drplace_portaldev`.`usuario_perfil` (`uperf_id`, `uperf_nome`, `uperf_status`, `uperf_statusAtivo`) VALUES (1, 'Comprador', 1, 1);
INSERT INTO `drplace_portaldev`.`usuario_perfil` (`uperf_id`, `uperf_nome`, `uperf_status`, `uperf_statusAtivo`) VALUES (2, 'Anunciante', 1, 1);
INSERT INTO `drplace_portaldev`.`usuario_perfil` (`uperf_id`, `uperf_nome`, `uperf_status`, `uperf_statusAtivo`) VALUES (3, 'Corretores', 1, 1);
INSERT INTO `drplace_portaldev`.`usuario_perfil` (`uperf_id`, `uperf_nome`, `uperf_status`, `uperf_statusAtivo`) VALUES (4, 'Imobiliárias', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `drplace_portaldev`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `drplace_portaldev`;
INSERT INTO `drplace_portaldev`.`usuario` (`usu_id`, `fk_id_cidade`, `fk_id_perfil`, `usu_token`, `usu_nome`, `usu_cpf`, `usu_senha`, `usu_rg`, `usu_endereco`, `usu_numero`, `usu_bairro`, `usu_complemento`, `usu_cep`, `usu_dataCadastro`, `usu_telefone1`, `usu_telefone2`, `usu_celular1`, `usu_celular2`, `usu_whatsapp1`, `usu_whatsapp2`, `usu_radio1`, `usu_site`, `usu_facebook`, `usu_instagram`, `usu_twitter`, `usu_email1`, `usu_email2`, `usu_confirmado`, `usu_status`, `usu_statusAtivo`, `usu_admin`) VALUES (1, 1, 2, 'dfa5c408a798ee7adff0450f6113a400fbe344467bd8157da39b95ed1f8a241bd2e8d24d346885e7fe5df67c7d7a1acdb6a24178d4a05115d878fdf9dbd480d0', 'André Severino', '358.616.488-24', '2113238cc44b264aaa55e8421c0c0ac6733f5601541f489c97fd555961f139b4', NULL, NULL, NULL, NULL, NULL, NULL, '2016-06-17 05:05:01', NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'ieasy@andrewd.com.br', NULL, 1, 1, 1, 1);

COMMIT;

